from flask import Blueprint, request, jsonify, session
from database import get_db, safe_execute, log_audit
from psycopg2.extras import RealDictCursor
from blueprints.auth import role_required
import uuid

financial_bp = Blueprint('financial', __name__)

@financial_bp.route('/api/record-payment', methods=['POST'])
@role_required(['receptionist', 'admin'])
def record_payment():
    data = request.json
    invoice_id = data.get('invoice_id')
    amount = float(data.get('amount', 0))
    method = data.get('method', 'Cash')
    idempotency_key = data.get('idempotency_key') # UUID generated by frontend

    if not idempotency_key:
        return jsonify({"error": "Missing transaction key."}), 400

    conn = get_db()
    try:
        cursor = conn.cursor(cursor_factory=RealDictCursor)
        
        # 1. Idempotency Check (Did we already process this exact click?)
        cursor.execute("SELECT id FROM payments WHERE idempotency_key = %s", (idempotency_key,))
        if cursor.fetchone():
            return jsonify({"status": "already_processed"}), 200
            
        # 2. Check Invoice Balance
        cursor.execute("SELECT total_amount FROM invoices WHERE id = %s", (invoice_id,))
        invoice = cursor.fetchone()
        
        cursor.execute("SELECT COALESCE(SUM(amount), 0) as paid FROM payments WHERE invoice_id = %s AND status = 'SUCCESS'", (invoice_id,))
        already_paid = float(cursor.fetchone()['paid'])
        balance = float(invoice['total_amount']) - already_paid
        
        # Prevent Overpayment
        if amount > balance:
            amount = balance
            
        if amount > 0:
            # Record SUCCESS Payment
            cursor.execute("""
                INSERT INTO payments (invoice_id, amount, method, idempotency_key, status, recorded_by) 
                VALUES (%s, %s, %s, %s, 'SUCCESS', %s) RETURNING id
            """, (invoice_id, amount, method, idempotency_key, session.get('role')))
            
            # Update Invoice State
            new_status = 'PAID' if (already_paid + amount) >= float(invoice['total_amount']) else 'PARTIALLY_PAID'
            cursor.execute("UPDATE invoices SET status = %s WHERE id = %s", (new_status, invoice_id))
            
            # Audit
            log_audit('Invoice', invoice_id, "Payment Recorded", "N/A", new_status, f"₹{amount} via {method}")
            
        conn.commit()
        return jsonify({"status": "success", "new_balance": balance - amount})
        
    except Exception as e:
        conn.rollback()
        return jsonify({"error": str(e)}), 500
    finally:
        conn.close()
